### ISSUE TITLE
Request to update mentioned tool for Majiang paipu transformation

### ISSUE THREAD

**Issue by Apricot-S** [hidacow/Majiang_bot#1]
Hello,

Thank you for mentioning [Apricot-S/majiang-log](https://github.com/Apricot-S/majiang-log) in your project.

I wanted to let you know that the author of Majiang, [Satoshi Kobayashi](https://github.com/kobalab), has developed a similar tool called [kobalab/tenhou-url-log](https://github.com/kobalab/tenhou-url-log).
Could you consider mentioning this tool instead, or in addition to, the current one in your project description?

Thank you for your consideration.

**Comment by hidacow** [comment]
Thank you for notifying this, I have already added it to the readme.

**Comment by Apricot-S** [comment]
Thank you for your prompt response.
